[project]
name = "automatedtrading"
version = "0.1.0"
description = ""
authors = ["santhosh <skumarr53@gmail.com>"]
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "loguru>=0.7.2",
    "selenium>=4.20",
    "pyotp>=2.9.0",
    "fyers-apiv3>=3.1",
    "urllib3>=1.26.0",
    "pandas>=2.0.0",
    "hydra-core>=1.3",
    "APScheduler>=3.10.4",
    "Sphinx>=7.1.1",
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
    "numpy==1.24.4",
    "pyperclip>=1.9.0",
    "ta-lib>=0.4.32",
    "joblib>=1.4.2",
    "scikit-learn==1.3.2",
    "influxdb-client>=1.46.0",
    "tqdm>=4.66.5",
    "mlflow>=2.17.0",
    "seaborn>=0.13.2",
    "shap>=0.41.0",
    "imblearn>=0.0",
    "yfinance>=0.2.40",
    "streamlit>=1.51.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.3"
]
