# Data API payload
BASE_PAYLOAD:
  symbol: "{symbol}"
  resolution: "{interval}"
  date_format: "0"
  range_from: "{start_epoch_time}"
  range_to: "{end_epoch_time}"
  cont_flag: "1"

CUSTOM_MODEL_WINDOW_WEIGHTS:
  5: 0.20
  15: 0.20
  30: 0.20
  60: 0.20
  180: 0.10

TECHNICAL_INDICATORS_PARAMS:
  bollinger_bands__timeperiod: [10, 12, 15]
  rsi__timeperiod: [5, 7, 9]
  macd__fastperiod: [3, 5, 8]
  macd__slowperiod: [16, 19, 22]
  macd__signalperiod: [3, 5, 7]
  stochastic_oscillator__fastk_period: [5, 7, 9]
  adx__timeperiod: [7, 10, 12]
  ema__short_period: [5, 7, 9]
  ema__long_period: [12, 15, 18]
  atr__timeperiod: [5, 7, 10]
  cci__timeperiod: [5, 10, 12]
  ichimoku_cloud__conversion_line_period: [6, 7, 9]
  ichimoku_cloud__base_line_periods: [16, 19, 22]
  ichimoku_cloud__lagging_span2_periods: [22, 30, 44]
  ichimoku_cloud__displacement: [16, 19, 22]
  fibonacci_retracements__window: [78, 156, 234]

CUSTOM_MODEL_PARAMS:
  feature_selection__n_features: [10, 25, 50, None]
  Model_fit__n_estimators: [10, 50, 100, 200]
  Model_fit__max_depth: [3, 5, 10]
  Model_fit__min_samples_split: [20, 50, 100]
  Model_fit__min_samples_leaf: [10, 20, 50]

CUSTOM_MODEL_FEATURES:
  TECH_INDS: []
  CS_PATTERNS: []
  COMB:
    [
      "high_14d",
      "low_14d",
      "high_52w",
      "low_52w",
      "weighted_bid_price",
      "total_bid_volume",
      "weighted_ask_price",
      "total_ask_volume",
      "spread",
      "buy_sell_pressure_ratio",
      "intraday_price_range",
      "price_movement_open_close",
      "candlestick_length",
      "body_length",
      "body_mid_point",
      "body_to_length_ratio",
      "candlestick_length_prev_1",
      "body_length_prev_1",
      "body_mid_point_prev_1",
      "body_to_length_ratio_prev_1",
      "candlestick_length_prev_2",
      "body_length_prev_2",
      "body_mid_point_prev_2",
      "body_to_length_ratio_prev_2",
      "high_1h",
      "low_1h",
      "high_5h",
      "low_5h",
      "high_1d",
      "low_1d",
      "volume_pct_change_last_interval",
      "volume_pct_change_mean_3",
      "volume_pct_change_mean_5",
      "bollinger_upperband_param1",
      "bollinger_middleband_param1",
      "bollinger_lowerband_param1",
      "bollinger_upperband_param2",
      "bollinger_middleband_param2",
      "bollinger_lowerband_param2",
      "bollinger_upperband_param3",
      "bollinger_middleband_param3",
      "bollinger_lowerband_param3",
      "rsi_param1",
      "rsi_param2",
      "rsi_param3",
      "macd_param1",
      "macd_signal_param1",
      "macd_hist_param1",
      "macd_param2",
      "macd_signal_param2",
      "macd_hist_param2",
      "macd_param3",
      "macd_signal_param3",
      "macd_hist_param3",
      "stochastic_k_param1",
      "stochastic_d_param1",
      "stochastic_k_param2",
      "stochastic_d_param2",
      "stochastic_k_param3",
      "stochastic_d_param3",
      "adx_param1",
      "adx_param2",
      "adx_param3",
      "ema_short_param1",
      "ema_long_param1",
      "ema_short_param2",
      "ema_long_param2",
      "ema_short_param3",
      "ema_long_param3",
      "vwap",
      "atr_param1",
      "atr_param2",
      "atr_param3",
      "obv",
      "sar",
      "cci_param1",
      "cci_param2",
      "cci_param3",
      "ichimoku_conversion_line_param1",
      "ichimoku_base_line_param1",
      "ichimoku_leading_span_a_param1",
      "ichimoku_leading_span_b_param1",
      "ichimoku_lagging_span_param1",
      "ichimoku_price_above_cloud_param1",
      "ichimoku_conversion_line_param2",
      "ichimoku_base_line_param2",
      "ichimoku_leading_span_a_param2",
      "ichimoku_leading_span_b_param2",
      "ichimoku_lagging_span_param2",
      "ichimoku_price_above_cloud_param2",
      "ichimoku_conversion_line_param3",
      "ichimoku_base_line_param3",
      "ichimoku_leading_span_a_param3",
      "ichimoku_leading_span_b_param3",
      "ichimoku_lagging_span_param3",
      "ichimoku_price_above_cloud_param3",
      "is_green",
      "is_green_prev_1",
      "is_green_prev_2",
      "hour_of_day",
      "day_of_week",
      "month_of_year",
      "quarter_of_year",
    ]
