common_columns:
  # Ticker and Core Columns
  epoch_time: 'epoch_time'
  open: 'open'
  high: 'high'
  low: 'low'
  close: 'close'
  volume: 'volume'
  date: 'date'
  symbol: 'symbol'
  total_buy_qty: 'total_buy_qty'
  total_sell_qty: 'total_sell_qty'
  last_traded_qty: 'last_traded_qty'
  last_traded_time: 'last_traded_time'
  last_traded_price: 'last_traded_price'
  change_percent: 'change_percent'
  tick_size: 'tick_size'
  change: 'change'
  average_traded_price: 'average_traded_price'
  lower_circuit: 'lower_circuit'
  upper_circuit: 'upper_circuit'
  expiry: 'expiry'
  open_interest: 'open_interest'
  open_interest_flag: 'open_interest_flag'
  previous_day_open_interest: 'previous_day_open_interest'
  open_interest_percent: 'open_interest_percent'

  # Additional Indicators
  upperband_param1: 'upperband_param1'
  middleband_param1: 'middleband_param1'
  lowerband_param1: 'lowerband_param1'
  rsi_param1: 'rsi_param1'
  rsi_param2: 'rsi_param2'
  rsi_param3: 'rsi_param3'
  macd_param1: 'macd_param1'
  macd_param2: 'macd_param2'
  macd_param3: 'macd_param3'
  macd_signal_param1: 'macd_signal_param1'
  macd_signal_param2: 'macd_signal_param2'
  macd_signal_param3: 'macd_signal_param3'
  macd_hist_param1: 'macd_hist_param1'
  macd_hist_param2: 'macd_hist_param2'
  macd_hist_param3: 'macd_hist_param3'
  adx_param1: 'adx_param1'
  adx_param2: 'adx_param2'
  adx_param3: 'adx_param3'
  ema_short_param1: 'ema_short_param1'
  ema_long_param1: 'ema_long_param1'
  ema_short_param2: 'ema_short_param2'
  ema_long_param2: 'ema_long_param2'
  ema_short_param3: 'ema_short_param3'
  ema_long_param3: 'ema_long_param3'
  vwap: 'vwap'
  obv: 'obv'
  sar: 'sar'
  cci_param1: 'cci_param1'
  cci_param2: 'cci_param2'
  cci_param3: 'cci_param3'
  atr_param1: 'atr_param1'
  atr_param2: 'atr_param2'
  atr_param3: 'atr_param3'

  # Bollinger Bands
  bollinger_upperband_param1: 'bollinger_upperband_param1'
  bollinger_middleband_param1: 'bollinger_middleband_param1'
  bollinger_lowerband_param1: 'bollinger_lowerband_param1'
  bollinger_upperband_param2: 'bollinger_upperband_param2'
  bollinger_middleband_param2: 'bollinger_middleband_param2'
  bollinger_lowerband_param2: 'bollinger_lowerband_param2'
  bollinger_upperband_param3: 'bollinger_upperband_param3'
  bollinger_middleband_param3: 'bollinger_middleband_param3'
  bollinger_lowerband_param3: 'bollinger_lowerband_param3'

  # Ichimoku Indicators
  ichimoku_conversion_line_param1: 'ichimoku_conversion_line_param1'
  ichimoku_base_line_param1: 'ichimoku_base_line_param1'
  ichimoku_leading_span_a_param1: 'ichimoku_leading_span_a_param1'
  ichimoku_leading_span_b_param1: 'ichimoku_leading_span_b_param1'
  ichimoku_lagging_span_param1: 'ichimoku_lagging_span_param1'
  ichimoku_price_above_cloud_param1: 'ichimoku_price_above_cloud_param1'
  ichimoku_conversion_line_param2: 'ichimoku_conversion_line_param2'
  ichimoku_base_line_param2: 'ichimoku_base_line_param2'
  ichimoku_leading_span_a_param2: 'ichimoku_leading_span_a_param2'
  ichimoku_leading_span_b_param2: 'ichimoku_leading_span_b_param2'
  ichimoku_lagging_span_param2: 'ichimoku_lagging_span_param2'
  ichimoku_price_above_cloud_param2: 'ichimoku_price_above_cloud_param2'
  ichimoku_conversion_line_param3: 'ichimoku_conversion_line_param3'
  ichimoku_base_line_param3: 'ichimoku_base_line_param3'
  ichimoku_leading_span_a_param3: 'ichimoku_leading_span_a_param3'
  ichimoku_leading_span_b_param3: 'ichimoku_leading_span_b_param3'
  ichimoku_lagging_span_param3: 'ichimoku_lagging_span_param3'
  ichimoku_price_above_cloud_param3: 'ichimoku_price_above_cloud_param3'

  # Stochastic Oscillator
  stochastic_k_param1: 'stochastic_k_param1'
  stochastic_d_param1: 'stochastic_d_param1'
  stochastic_k_param2: 'stochastic_k_param2'
  stochastic_d_param2: 'stochastic_d_param2'
  stochastic_k_param3: 'stochastic_k_param3'
  stochastic_d_param3: 'stochastic_d_param3'

  # Time Series Columns
  high_1h: 'high_1h'
  low_1h: 'low_1h'
  high_5h: 'high_5h'
  low_5h: 'low_5h'
  high_1d: 'high_1d'
  low_1d: 'low_1d'
  high_14d: 'high_14d'
  low_14d: 'low_14d'
  high_52w: 'high_52w'
  low_52w: 'low_52w'
  volume_pct_change_last_interval: 'volume_pct_change_last_interval'
  volume_pct_change_mean_3: 'volume_pct_change_mean_3'
  volume_pct_change_mean_5: 'volume_pct_change_mean_5'
  hour_of_day: 'hour_of_day'
  day_of_week: 'day_of_week'
  month_of_year: 'month_of_year'
  quarter_of_year: 'quarter_of_year'
  candlestick_gap: 'candlestick_gap'

  # Candlestick Pattern Columns
  candlestick_length: 'candlestick_length'
  body_length: 'body_length'
  body_mid_point: 'body_mid_point'
  is_green: 'is_green'
  body_to_length_ratio: 'body_to_length_ratio'
  candlestick_length_prev_1: 'candlestick_length_prev_1'
  body_length_prev_1: 'body_length_prev_1'
  body_mid_point_prev_1: 'body_mid_point_prev_1'
  is_green_prev_1: 'is_green_prev_1'
  body_to_length_ratio_prev_1: 'body_to_length_ratio_prev_1'
  candlestick_length_prev_2: 'candlestick_length_prev_2'
  body_length_prev_2: 'body_length_prev_2'
  body_mid_point_prev_2: 'body_mid_point_prev_2'
  is_green_prev_2: 'is_green_prev_2'
  body_to_length_ratio_prev_2: 'body_to_length_ratio_prev_2'
  high_3d: 'high_3d'
  low_3d: 'low_3d'
  high_5d: 'high_5d'
  low_5d: 'low_5d'

  # Order Book Derived Columns
  weighted_bid_price: 'weighted_bid_price'
  total_bid_volume: 'total_bid_volume'
  weighted_ask_price: 'weighted_ask_price'
  total_ask_volume: 'total_ask_volume'
  spread: 'spread'
  buy_sell_pressure_ratio: 'buy_sell_pressure_ratio'
  intraday_price_range: 'intraday_price_range'
  price_movement_open_close: 'price_movement_open_close'