# Import common column definitions
indicators_cols:
  - ${columns.common_columns.upperband_param1}
  - ${columns.common_columns.middleband_param1}
  - ${columns.common_columns.lowerband_param1}
  - ${columns.common_columns.upperband_param2}
  - ${columns.common_columns.middleband_param2}
  - ${columns.common_columns.lowerband_param2}
  - ${columns.common_columns.upperband_param3}
  - ${columns.common_columns.middleband_param3}
  - ${columns.common_columns.lowerband_param3}
  - ${columns.common_columns.rsi_param1}
  - ${columns.common_columns.rsi_param2}
  - ${columns.common_columns.rsi_param3}
  - ${columns.common_columns.macd_param1}
  - ${columns.common_columns.signal_param1}
  - ${columns.common_columns.hist_param1}
  - ${columns.common_columns.macd_param2}
  - ${columns.common_columns.signal_param2}
  - ${columns.common_columns.hist_param2}
  - ${columns.common_columns.macd_param3}
  - ${columns.common_columns.signal_param3}
  - ${columns.common_columns.hist_param3}
  - ${columns.common_columns.stochastic_k_param1}
  - ${columns.common_columns.stochastic_d_param1}
  - ${columns.common_columns.stochastic_k_param2}
  - ${columns.common_columns.stochastic_d_param2}
  - ${columns.common_columns.stochastic_k_param3}
  - ${columns.common_columns.stochastic_d_param3}
  - ${columns.common_columns.adx_param1}
  - ${columns.common_columns.adx_param2}
  - ${columns.common_columns.adx_param3}
  - ${columns.common_columns.ema_short_param1}
  - ${columns.common_columns.ema_long_param1}
  - ${columns.common_columns.ema_short_param2}
  - ${columns.common_columns.ema_long_param2}
  - ${columns.common_columns.ema_short_param3}
  - ${columns.common_columns.ema_long_param3}
  - ${columns.common_columns.vwap}
  - ${columns.common_columns.atr_param1}
  - ${columns.common_columns.atr_param2}
  - ${columns.common_columns.atr_param3}
  - ${columns.common_columns.obv}
  - ${columns.common_columns.sar}
  - ${columns.common_columns.cci_param1}
  - ${columns.common_columns.cci_param2}
  - ${columns.common_columns.cci_param3}
  - ${columns.common_columns.conversion_line_param1}
  - ${columns.common_columns.base_line_param1}
  - ${columns.common_columns.leading_span_a_param1}
  - ${columns.common_columns.leading_span_b_param1}
  - ${columns.common_columns.lagging_span_param1}
  - ${columns.common_columns.price_above_cloud_param1}
  - ${columns.common_columns.conversion_line_param2}
  - ${columns.common_columns.base_line_param2}
  - ${columns.common_columns.leading_span_a_param2}
  - ${columns.common_columns.leading_span_b_param2}
  - ${columns.common_columns.lagging_span_param2}
  - ${columns.common_columns.price_above_cloud_param2}
  - ${columns.common_columns.conversion_line_param3}
  - ${columns.common_columns.base_line_param3}
  - ${columns.common_columns.leading_span_a_param3}
  - ${columns.common_columns.leading_span_b_param3}
  - ${columns.common_columns.lagging_span_param3}
  - ${columns.common_columns.price_above_cloud_param3}
