# src/config/columns/model_columns.yaml
custom_cs_cols:
  - ${columns.common_columns.candlestick_length}
  - ${columns.common_columns.body_length}
  - ${columns.common_columns.body_mid_point}
  - ${columns.common_columns.is_green}
  - ${columns.common_columns.body_to_length_ratio}
  - ${columns.common_columns.candlestick_length_prev_1}
  - ${columns.common_columns.body_length_prev_1}
  - ${columns.common_columns.body_mid_point_prev_1}
  - ${columns.common_columns.is_green_prev_1}
  - ${columns.common_columns.body_to_length_ratio_prev_1}
  - ${columns.common_columns.candlestick_length_prev_2}
  - ${columns.common_columns.body_length_prev_2}
  - ${columns.common_columns.body_mid_point_prev_2}
  - ${columns.common_columns.is_green_prev_2}
  - ${columns.common_columns.body_to_length_ratio_prev_2}
  - ${columns.common_columns.high_1h}
  - ${columns.common_columns.low_1h}
  - ${columns.common_columns.high_5h}
  - ${columns.common_columns.low_5h}
  - ${columns.common_columns.high_1d}
  - ${columns.common_columns.low_1d}
  - ${columns.common_columns.high_3d}
  - ${columns.common_columns.low_3d}
  - ${columns.common_columns.high_5d}
  - ${columns.common_columns.low_5d}
  - ${columns.common_columns.high_14d}
  - ${columns.common_columns.low_14d}
  - ${columns.common_columns.high_52w}
  - ${columns.common_columns.low_52w}
  - ${columns.common_columns.volume_pct_change_last_interval}
  - ${columns.common_columns.volume_pct_change_mean_3}
  - ${columns.common_columns.volume_pct_change_mean_5}
  - ${columns.common_columns.hour_of_day}
  - ${columns.common_columns.day_of_week}
  - ${columns.common_columns.month_of_year}
  - ${columns.common_columns.quarter_of_year}
  - ${columns.common_columns.candlestick_gap}
