short_num_cols:
  - ${columns.common_columns.candlestick_length}
  - ${columns.common_columns.body_length}
  - ${columns.common_columns.body_mid_point}
  - ${columns.common_columns.body_to_length_ratio}
  - ${columns.common_columns.candlestick_length_prev_1}
  - ${columns.common_columns.body_length_prev_1}
  - ${columns.common_columns.body_mid_point_prev_1}
  - ${columns.common_columns.body_to_length_ratio_prev_1}
  - ${columns.common_columns.candlestick_length_prev_2}
  - ${columns.common_columns.body_length_prev_2}
  - ${columns.common_columns.body_mid_point_prev_2}
  - ${columns.common_columns.body_to_length_ratio_prev_2}
  - ${columns.common_columns.high_1h}
  - ${columns.common_columns.low_1h}
  - ${columns.common_columns.high_5h}
  - ${columns.common_columns.low_5h}
  - ${columns.common_columns.high_1d}
  - ${columns.common_columns.low_1d}
  - ${columns.common_columns.volume_pct_change_last_interval}
  - ${columns.common_columns.volume_pct_change_mean_3}
  - ${columns.common_columns.volume_pct_change_mean_5}
  - ${columns.common_columns.bollinger_upperband_param1}
  - ${columns.common_columns.bollinger_middleband_param1}
  - ${columns.common_columns.bollinger_lowerband_param1}
  - ${columns.common_columns.bollinger_upperband_param2}
  - ${columns.common_columns.bollinger_middleband_param2}
  - ${columns.common_columns.bollinger_lowerband_param2}
  - ${columns.common_columns.bollinger_upperband_param3}
  - ${columns.common_columns.bollinger_middleband_param3}
  - ${columns.common_columns.bollinger_lowerband_param3}
  - ${columns.common_columns.rsi_param1}
  - ${columns.common_columns.rsi_param2}
  - ${columns.common_columns.rsi_param3}
  - ${columns.common_columns.macd_param1}
  - ${columns.common_columns.macd_signal_param1}
  - ${columns.common_columns.macd_hist_param1}
  - ${columns.common_columns.macd_param2}
  - ${columns.common_columns.macd_signal_param2}
  - ${columns.common_columns.macd_hist_param2}
  - ${columns.common_columns.macd_param3}
  - ${columns.common_columns.macd_signal_param3}
  - ${columns.common_columns.macd_hist_param3}
  - ${columns.common_columns.stochastic_k_param1}
  - ${columns.common_columns.stochastic_d_param1}
  - ${columns.common_columns.stochastic_k_param2}
  - ${columns.common_columns.stochastic_d_param2}
  - ${columns.common_columns.stochastic_k_param3}
  - ${columns.common_columns.stochastic_d_param3}
  - ${columns.common_columns.adx_param1}
  - ${columns.common_columns.adx_param2}
  - ${columns.common_columns.adx_param3}
  - ${columns.common_columns.ema_short_param1}
  - ${columns.common_columns.ema_long_param1}
  - ${columns.common_columns.ema_short_param2}
  - ${columns.common_columns.ema_long_param2}
  - ${columns.common_columns.ema_short_param3}
  - ${columns.common_columns.ema_long_param3}
  - ${columns.common_columns.vwap}
  - ${columns.common_columns.atr_param1}
  - ${columns.common_columns.atr_param2}
  - ${columns.common_columns.atr_param3}
  - ${columns.common_columns.obv}
  - ${columns.common_columns.sar}
  - ${columns.common_columns.cci_param1}
  - ${columns.common_columns.cci_param2}
  - ${columns.common_columns.cci_param3}
  - ${columns.common_columns.ichimoku_conversion_line_param1}
  - ${columns.common_columns.ichimoku_base_line_param1}
  - ${columns.common_columns.ichimoku_leading_span_a_param1}
  - ${columns.common_columns.ichimoku_leading_span_b_param1}
  - ${columns.common_columns.ichimoku_lagging_span_param1}
  - ${columns.common_columns.ichimoku_price_above_cloud_param1}
  - ${columns.common_columns.ichimoku_conversion_line_param2}
  - ${columns.common_columns.ichimoku_base_line_param2}
  - ${columns.common_columns.ichimoku_leading_span_a_param2}
  - ${columns.common_columns.ichimoku_leading_span_b_param2}
  - ${columns.common_columns.ichimoku_lagging_span_param2}
  - ${columns.common_columns.ichimoku_price_above_cloud_param2}
  - ${columns.common_columns.ichimoku_conversion_line_param3}
  - ${columns.common_columns.ichimoku_base_line_param3}
  - ${columns.common_columns.ichimoku_leading_span_a_param3}
  - ${columns.common_columns.ichimoku_leading_span_b_param3}
  - ${columns.common_columns.ichimoku_lagging_span_param3}
  - ${columns.common_columns.ichimoku_price_above_cloud_param3}

long_num_cols:
  - ${columns.common_columns.high_14d}
  - ${columns.common_columns.low_14d}
  - ${columns.common_columns.high_52w}
  - ${columns.common_columns.low_52w}
  - ${columns.common_columns.weighted_bid_price}
  - ${columns.common_columns.total_bid_volume}
  - ${columns.common_columns.weighted_ask_price}
  - ${columns.common_columns.total_ask_volume}
  - ${columns.common_columns.spread}
  - ${columns.common_columns.buy_sell_pressure_ratio}
  - ${columns.common_columns.intraday_price_range}
  - ${columns.common_columns.price_movement_open_close}