# src/config/model/params.yaml
pipeline_params:
  feature_selection__n_features: [10, 25, 50]

model_params:
  GBC:
    model_fit__n_estimators: [10, 50, 100]  # Hyperparameters for models
    model_fit__max_depth: [3, 5]
    model_fit__min_samples_split: [20, 50]
    model_fit__min_samples_leaf: [10, 20, 50]
  RFC:
    model_fit__n_estimators: [10, 50, 100]  # Hyperparameters for models
    model_fit__max_depth: [3, 5]
    model_fit__min_samples_split: [20, 50]
    model_fit__min_samples_leaf: [10, 20, 50]
  MLP:
    model_fit__hidden_layer_sizes: [[100], [50, 50]]
    model_fit__activation: ['relu']
    model_fit__solver: ['adam', 'sgd']
    model_fit__alpha: [0.0001, 0.001, 0.01]
    model_fit__learning_rate: ['adaptive']
  KNN:
    model_fit__n_neighbors: [5, 10, 15]
    model_fit__weights: ['uniform', 'distance']
  LR:
    model_fit__penalty: ['l2']  # Regularization type
    model_fit__C: [0.1, 1.0, 10.0]  # Inverse of regularization strength
    model_fit__solver: ['liblinear', 'lbfgs']  # Solver
    model_fit__max_iter: [100, 200]  # Maximum iterations for convergence
  


technical_indicators_params:
  bollinger_bands__timeperiod: [10, 12, 15]
  rsi__timeperiod: [5, 7, 9]
  macd__fastperiod: [3, 5, 8]
  macd__slowperiod: [16, 19, 22]
  macd__signalperiod: [3, 5, 7]
  stochastic_oscillator__fastk_period: [5, 7, 9]
  adx__timeperiod: [7, 10, 12]
  ema__short_period: [5, 7, 9]
  ema__long_period: [12, 15, 18]
  atr__timeperiod: [5, 7, 10]
  cci__timeperiod: [5, 10, 12]
  ichimoku_cloud__conversion_line_period: [6, 7, 9]
  ichimoku_cloud__base_line_periods: [16, 19, 22]
  ichimoku_cloud__lagging_span2_periods: [22, 30, 44]
  ichimoku_cloud__displacement: [16, 19, 22]
  fibonacci_retracements__window: [78, 156, 234]
# Custom model
custom_model_windows: [5, 15, 30, 60, 180]

