pipeline_configs:
  Pipeline_1:
    std_scale: false
    feature_selector: SHAP
    imbalance_technique: SMOTE
    model: GBC

  Pipeline_2:
    std_scale: true
    feature_selector: SHAP
    imbalance_technique: SMOTE
    model: MLP